// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-3NbgJK-Qjo6v0YeTxM0dGB107NLTfnA',
    appId: '1:344599295984:web:71cdcefcce080a9f880f35',
    messagingSenderId: '344599295984',
    projectId: 'chatrooms-7aee4',
    authDomain: 'chatrooms-7aee4.firebaseapp.com',
    storageBucket: 'chatrooms-7aee4.appspot.com',
    measurementId: 'G-Q4C2N8Z233',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI2fFVKV3yqRPJLA3kp0wk61ktoYzyC_0',
    appId: '1:344599295984:android:3b5050dbb87c5bb3880f35',
    messagingSenderId: '344599295984',
    projectId: 'chatrooms-7aee4',
    storageBucket: 'chatrooms-7aee4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNwoYzNHZMqB8cu5LRdo7K_0g0CTN3unQ',
    appId: '1:344599295984:ios:2e971a9ea138cdca880f35',
    messagingSenderId: '344599295984',
    projectId: 'chatrooms-7aee4',
    storageBucket: 'chatrooms-7aee4.appspot.com',
    iosClientId: '344599295984-ri8okd5u3uhl61hg7k58cuqtb8qvckdd.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatrooms',
  );
}
